// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/polyse/frontend-service/internal/api"
)

// Injectors from wire.go:

func initFrontendService(c *config) (*api.API, func(), error) {
	appConfig, err := initFrontendServiceCfg(c)
	if err != nil {
		return nil, nil, err
	}
	apiAPI, err := api.NewApp(appConfig)
	if err != nil {
		return nil, nil, err
	}
	return apiAPI, func() {
	}, nil
}
